# Dockerfile for Random Number Service
# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY ../../requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY ../../src/generate-random-number.py .
COPY ../../src/common/* ./common/

# Expose the port the app runs on
EXPOSE 5000

# Define the command to run the application
CMD ["python", "generate-random-number.py"]