apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-config
              mountPath: /etc/postgresql
              subPath: postgresql.conf
            - name: pg-hba-config
              mountPath: /etc/postgresql
              subPath: pg_hba.conf
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
            items:
              - key: postgresql.conf
                path: postgresql.conf
        - name: pg-hba-config
          configMap:
            name: postgres-config
            items:
              - key: pg_hba.conf
                path: pg_hba.conf