apiVersion: v1
kind: Service
metadata:
  name: {{ include "random.random.fullname" . }}
  labels:
    {{- include "random.labels" . | nindent 4 }}
spec:
  type: {{ .Values.random.service.type }}
  ports:
    - port: {{ .Values.random.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "random.random.selectorLabels" . | nindent 4 }}
