apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "random.random.fullname" . }}
  labels:
    {{- include "random.labels" . | nindent 4 }}
spec:
  {{- if not .Values.random.autoscaling.enabled }}
  replicas: {{ .Values.random.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "random.random.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.random.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "random.random.selectorLabels" . | nindent 8 }}
        {{- with .Values.random.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.random.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "random.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.random.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_NAME
              value: {{ .Values.postgresql.auth.database }}
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_PORT
              value: "5432"
          securityContext:
            {{- toYaml .Values.random.securityContext | nindent 12 }}
          image: "{{ .Values.random.image.repository }}:{{ .Values.random.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.random.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.random.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.random.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.random.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.random.resources | nindent 12 }}
          {{- with .Values.random.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.random.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.random.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.random.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.random.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
