apiVersion: v1
kind: Service
metadata:
  name: {{ include "random.user.fullname" . }}
  labels:
    {{- include "random.labels" . | nindent 4 }}
spec:
  type: {{ .Values.user.service.type }}
  ports:
    - port: {{ .Values.user.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "random.user.selectorLabels" . | nindent 4 }}
