apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "random.user.fullname" . }}
  labels:
    {{- include "random.labels" . | nindent 4 }}
spec:
  {{- if not .Values.user.autoscaling.enabled }}
  replicas: {{ .Values.user.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "random.user.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.user.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "random.user.selectorLabels" . | nindent 8 }}
        {{- with .Values.user.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.user.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "random.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.user.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.user.securityContext | nindent 12 }}
          image: "{{ .Values.user.image.repository }}:{{ .Values.user.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.user.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.user.service.port }}
              protocol: TCP
          env:
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_NAME
              value: users
            - name: DB_HOST
              value: {{ include "random.user.fullname" . }}-postgresql
            - name: DB_PORT
              value: "5432"
          livenessProbe:
            {{- toYaml .Values.user.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.user.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.user.resources | nindent 12 }}
          {{- with .Values.user.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.user.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.user.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.user.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.user.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
